[package]
name = "engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
common = { workspace = true }
model = { workspace = true }
journal = { workspace = true }
state = { workspace = true }
feel = { workspace = true }
